vocdoni/vocdoni-ui

components/dashboard/process-list.tsx, pages/dashboard/index.tsx
[VOC-56](https://linear.app/aragon/issue/VOC-57/voting-list-page)
Create dashboard page with the voting process list
=> [VOC-57] Create dashboard page

components/pages/dashboard/vote-detail/index.tsx, components/pages/pub/votes/index.tsx, i18n/locales/ca.json, i18n/locales/en.json, i18n/locales/es.json
Added total votes in public voting page and dashboard question details
=> Added total votes

components/blocks/vote-question-card/question-results.tsx
Added a minimum width for answer's result progressbar
=> Minimum width for progressbar

components/blocks/vote-question-card/index.tsx, components/blocks/vote-question-card/question-no-results-available.tsx, components/blocks/vote-question-card/question-results.tsx
Show the answers in the detail page instead of only the `no_results_available` text
=> [VPLZ-204] Show the answers in the detail page

components/elements/radio.tsx
Fixed checkbox size shrinking when the text answer is too long
=> [VPLZ-222] Fixed checkbox size

components/pages/dashboard/vote-detail/index.tsx, components/pages/pub/votes/index.tsx
In the detailed voting process page (admin) and in the public voting page, when a process has ended, add the information about when this process have ended.
=> [VPLZ-219] Added end date in process

i18n/locales/ca.json, i18n/locales/en.json, i18n/locales/es.json, pages/_app.tsx
[DVOT-85] Added several meta tags for SEO
[DVOT-85]: https://aragonassociation.atlassian.net/browse/DVOT-85
=> [DVOT-85] SEO Review

components/pages/app/external-dependencies/ruddlestack.tsx, components/pages/app/header/entity.tsx, components/pages/dashboard/create-proposal-card.tsx, components/pages/dashboard/header.tsx, components/pages/entity/new/credentials.tsx, components/pages/entity/new/entity-ready.tsx, components/pages/entity/new/metadata.tsx, components/pages/home/components/hero-banner/index.tsx, components/pages/votes/new/census.tsx, components/pages/votes/new/metadata.tsx, components/pages/votes/new/options.tsx, hooks/entity-creation.tsx, hooks/process-creation.tsx
[DVOT-122] Added ruddlestack events on the platform
[DVOT-122]: https://aragonassociation.atlassian.net/browse/DVOT-122
=> [DVOT-122] Add events on the platform

components/pages/app/external-dependencies/ruddlestack.tsx
[DVOT-122] Fix analytics
[DVOT-122]: https://aragonassociation.atlassian.net/browse/DVOT-122
=> [DVOT-122] Fix analytics

package.json
=> Updated dvote-js to 1.13.2

hooks/entity-creation.tsx, hooks/use-wallet.tsx, recoil/atoms/accounts.ts, recoil/atoms/wallet.ts, recoil/selectors/account.ts
Fix error on the header when the user create new account
=> Set recoil wallet when register wallet using context

components/blocks/help-text.tsx
[DVOT-128] Fixed help tooltips
[DVOT-128]: https://aragonassociation.atlassian.net/browse/DVOT-128
=> [DVOT-128] Help tooltips not showing correct in chrome

.github/workflows/main.yml, components/blocks/cookies-banner.tsx, components/pages/app/external-dependencies/ruddlestack.tsx, const/env.ts, env-config.js, hooks/cookies.tsx, hooks/rudderstack.tsx, i18n/locales/ca.json, i18n/locales/en.json, i18n/locales/es.json, i18n/locales/eu.json, i18n/locales/fr.json, i18n/locales/it.json, i18n/locales/zh.json, pages/cookies.tsx
Updated several behaviors for cookies policy, tracking and acceptance banner
=> [DVOT-118] Updated cookies policy

CHANGELOG.md, components/blocks/text-editor/index.tsx, components/pages/votes/new/metadata.tsx
Fix problem when the user fill the description the others fields will be errase
=> [DVOT-197] Fix description problem

components/blocks/form.tsx, components/elements/inputs.tsx, components/pages/entity/new/credentials.tsx, components/pages/login/form.tsx, i18n/locales/ca.json, i18n/locales/en.json, i18n/locales/es.json
- Add new functionality on the password fields to check the current writted text
=> [DVOT-105] Add Eye on password fields

.github/workflows/main.yml, env-config.js
=> Update new prod backend to point to

components/pages/pub/votes/components/confirm-modal/questions-list.tsx, components/pages/pub/votes/index.tsx
Add bold titles to the voting modal and prevent the browser popup to appear when trying to close the tab after voting
=> Add omnium changes

components/pages/votes/new/components/date-selector.tsx
+ Added "Application" component around DateTimePicker for allowing customization.
+ Added theme color palette (Vocdoni green) for the DateTimePicker
=> DateTimePicker component customization

components/elements/typography.tsx, components/pages/votes/new/census.tsx, i18n/locales/ca.json, i18n/locales/en.json, i18n/locales/es.json
Added the new banner + translations
=> Added a disclaimer about "trusted ceremony" when selecting anonymous voting

components/blocks/card/image-header.tsx, components/elements/typography.tsx, components/pages/pub/votes/components/question-card.tsx
As per requests from @Martamord, I've reviewed some of the heading sizes in the voting page for mobile devices, balancing them a bit.
=> Adjusted font size for some headings in mobile devices
